server:
  port: 8081
spring:
  datasource:
    hikari:
      schema: user_service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_service
